apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: dwickizer1/mean:express_prod
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_DB_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
  labels:
    app: express
spec:
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer